{{- $fullName := include "cert-issuer.fullname" . -}}
{{- $domains := .Values.domains | required ".Values.domains must be an array of domain names" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cert-issuer.labels" . | nindent 4 }}
spec:
  acme:
{{- if .Values.acme }}
{{ .Values.acme | toYaml | indent 4 }}
{{- end }}
    solvers:
    - selector:
        dnsZones: {{ $domains | toYaml | nindent 8 }}
      dns01:
        route53:
          region: {{ .Values.aws.region }}
          accessKeyID: {{ .Values.aws.access_key_id }}
          secretAccessKeySecretRef:
            name: {{ $fullName }}-dns
            key: secret-access-key

