{{- $fullName := include "cert-issuer.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-dns
  labels:
    {{- include "cert-issuer.labels" . | nindent 4 }}
data:
  secret-access-key: {{ .Values.aws.secret_access_key | b64enc }}
