{{- $fullName := include "cert-issuer.fullname" . -}}
{{- $secretKey := .Values.aws.secret_access_key | required ".Values.aws.secret_access_key is missing" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-dns
  labels:
    {{- include "cert-issuer.labels" . | nindent 4 }}
data:
  secret-access-key: {{ $secretKey | b64enc | quote }}
